APP_NAME: "Movie_Ticketing_Sytem"
APP_PORT: 3000

DB_DRIVER: "postgres"
DB_HOST: "database-2.c2tuuysyqfj3.ap-south-1.rds.amazonaws.com"
DB_PORT: 5432
DB_NAME: "TicketingPortal"
DB_USER: "postgres"
DB_PASSWORD: "dbqwer"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"
